# Generated by Django 6.0.4 on 2026-04-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='category',
            new_name='author',
        ),
    ]
