# Generated by Django 6.0.4 on 2026-04-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_rename_category_author_rename_title_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='title',
        ),
    ]
