# Generated by Django 6.0.4 on 2026-04-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_rename_name_author_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='title',
            new_name='name',
        ),
    ]
